language: node_js
sudo: false
node_js:
- '4'
- '6'

before_script:
# If this command fails and you can't fix it, file an issue and add an exception to .nsprc
- npm run nsp-check

script:
- COVERAGE=y NODE_ENV=production npm test
- |
  echo <<-EOM
    Starting changelog linting, please take a look at

    - https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#writing-commit-messages

    and mention in a comment one of the mantainers if the travis build is failing here.
  EOM
- npm run travis-pullrequest-title-lint
- |
  COMMIT_COUNT=`git rev-list --count HEAD ^0d636c42d`
  if [[ $COMMIT_COUNT -eq 1 ]]; then
    echo "Lint the commit message on a 'single commit' pull request"
    git show -s --format=%B HEAD | ./node_modules/.bin/conventional-changelog-lint
  fi

after_script: npm run publish-coverage

notifications:
  irc:
    channels:
    #- irc.mozilla.org#amo-bots
    on_success: change
    on_failure: always
deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  skip_cleanup: true
  # This is the API key for npm user 'addons-robot'
  api_key:
    secure: gMZR5u6VxrXFxTigPlaoCre+SpFWf2dp3nsjYqYfvSW7eVqy9WtZpxOxJaNMn4Fwo+U8BVz7u23sugC/gm6JwjhIjVb20dwHhKJd1rjo4U+1Dbf9IdGysNWE6FYi3IKr2HpB/lht2HFb3+X01bLgB0xcTY459HOorAIDinTvrMMlmilV0S+sp9MeYjbcNl+tT71raVf4O2AJqsI1cA5yDLc3lhoNd87l7aB/+3AR3Vvbt0HymuzZJBz5dY5txxw2m53jPIj4Dxj6RMwsJ7fuEESkM0Da26ViOEuK+4zvwt/HhUFeDveKyOZklX7tLHg9m5MhOrnRsRRvGTxi+jIGlyO9NHhKMaK7Cvlp3K9DzTSpyilNFjEzmAE6H6HiI/DfdrmvD365RJU1SE/3R77c/n3GROmka/m9g6dJXteScoA2kitFizjnkMwPdPunZP2OXl8kUGeA3VIIDF03JXTFPz+bjNslmO0u5Y4vuKBy3fVhoxMd0c8hb+okCbkFJSwHVM4qWmLPYarN8I1XxmcVuJWbrjnFo8EAgaFXwge4PoglZsmCo0oDbM7IC0DirCsCiq4Fj+U2mrIA7k/9EVQ/i/3t2NCZ5xDdTyQzhqRx78lJt2Wr2lhx7kImiZ8SiFrIsAjkLvU4P8zE66eOpfgMAHdDDQAX9PA08Twyp1IG8Bk=
  on:
    tags: true
