language: node_js
sudo: false
node_js:
- '0.12'
- '4'
before_install:
- npm install -g npm
script: COVERAGE=y npm test
after_script: "npm install coveralls@2.11.8 && cat ./coverage/lcov.info | coveralls"
notifications:
  irc:
    channels:
    - irc.mozilla.org#amo-bots
    on_success: change
    on_failure: always
